### ISSUE TITLE
Allow CORS on custom ports

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#943] opened 2019-05-08 07:46 UTC
The comit node's configuration file allows you to customise the port on which the embedded comit-i will be served, but you can't start your own frontend on your own custom port with CORS enabled.

Tasks:
- Add an optional config field to `CndSettings` that represents a list of ports for which CORS will be enabled
- Automatically add the `web_gui` port to this list after startup if it is present
- Revise the CORS logic to just care about this list of ports and not whether `web_gui` is present
- Mention this logic with the associated usecase (running more than one or a separate UI) in the `build` section in the README

**Comment by D4nte** [comment] 2019-05-09 00:17
I am not sure I am 100% clear on CORS works but I'd expect that you clear the port for which the embedded comit-i is running.

I would not bother for non-embedded comit-is.

**Comment by bonomat** [comment] 2019-05-09 00:26
> I would not bother for non-embedded comit-is.

This is more a development issue: if you want to develop on comit-i (i.e. not embedded in comit-rs), then you should be able change the allowed CORS headers. Currently it defaults to `8080` but since this is such a common port, I personally had something running on this port. Also, if it defaults to a port, then you cant start up two comit-rs nodes and two (custom) comit-i nodes.

**Comment by thomaseizinger** [comment] 2019-05-09 03:03
IMO this needs to be fixed upstream (https://github.com/seanmonstar/warp/issues/196) instead of introducing more config options/code.

**Comment by thomaseizinger** [comment] 2019-05-28 03:09
Is this a duplicate of #825?

**Comment by D4nte** [comment] 2019-09-09 00:57
Re-open if it comes up again.

**Closed by D4nte** 2019-09-09 00:57 UTC
