### ISSUE TITLE
Add `hash_function` parameter to `comit-rfc-003` protocol header value

### ISSUE THREAD

**Issue by LLFourn** [comit-network/comit-rs#689] opened 2019-01-22 22:35 UTC
As per RFC-003. `SHA-256` is the only accepted value for now.

EDIT (Tobin): Being new to the project I have managed to get totally confused working on this issue and muddled the HTTP API exposed by comit-rs with the BAM API used to communicate between two nodes.  The HTTP API is __not__ in scope for this issue.  Please ignore all discussion (now hidden) below about HTTP, and I accept full responsibility for causing the confusion.

**Comment by tcharding** [comment] 2019-06-20 01:20
While working on this I've stumbled across a possible abstraction layer issue.  Discussed in slack but posting here for completeness ...

I think we have an abstraction layer problem, please correct me if I am wrong.  All paths are under `comit-netwok/comit-rs`.

`http_api/route_factory.rs` is specific to rfc003

```
    pub fn create<T: MetadataStore<SwapId>, S: state_store::StateStore, C: Client, SI: SwarmInfo>(
    ...
) -> BoxedFilter<(impl Reply,)> {
    let swaps = warp::path(http_api::PATH);
    let rfc003 = swaps.and(warp::path(RFC003));
    let metadata_store = warp::any().map(move || Arc::clone(&metadata_store));
    ...

```
However the rfc003 endpoint accepts JSON that includes `protocol{ name: rfc003, hash_function: SHA-256 }`

It seems that either the scheme is incorrect and should not include the protocol name or the endpoint is incorrect and should not be named `rfc003` but rather be protocol agnostic.

Any thoughts please?

**Comment by tcharding** [comment] 2019-06-20 01:27
The solution suggested in slack is to fix the abstraction within `http_api/route_factory.rs` to correctly honour the RFC abstractions.

**Comment by thomaseizinger** [comment] 2019-06-21 13:51
> However the rfc003 endpoint accepts JSON that includes `protocol{ name: rfc003, hash_function: SHA-256 }`

That is not quite true? AFAIK I can see, you only added the hash function to the body: https://github.com/comit-network/comit-rs/pull/1033/files#diff-e2095062fdaf2c357483a30b5df1773bR99

Which is fine in my opinion.

**Comment by D4nte** [comment] 2019-06-22 04:43
> > However the rfc003 endpoint accepts JSON that includes `protocol{ name: rfc003, hash_function: SHA-256 }`
> 
> That is not quite true? AFAIK I can see, you only added the hash function to the body: [comit-network/comit-rs/pull/1033/files#diff-e2095062fdaf2c357483a30b5df1773bR99](https://github.com/comit-network/comit-rs/pull/1033/files#diff-e2095062fdaf2c357483a30b5df1773bR99)
> 
> Which is fine in my opinion.

No changes have been pushed to `origin` for a while.

As a consumer of the API (when I rewrote the e2es), the `/rfc003` in the path is a pain. I suggest we put the hash and the protocol in the body.

Let's see how it looks once reay.

**Comment by thomaseizinger** [comment] 2019-06-22 09:58
> As a consumer of the API (when I rewrote the e2es), the `/rfc003` in the path is a pain. I suggest we put the hash and the protocol in the body.

The HTTP body (fields like the timeout, redeem identity, etc) depend on the protocol though. It would be even more of a pain to deserialize that accordingly if the protocol is in the body. Also, having static formats for messages is much more idiomatic and actually easier to work with in most cases (for the client).

What exactly was painful about having the protocol in the path?

**Comment by D4nte** [comment] 2019-06-23 09:13
> > As a consumer of the API (when I rewrote the e2es), the `/rfc003` in the path is a pain. I suggest we put the hash and the protocol in the body.
> 
> The HTTP body (fields like the timeout, redeem identity, etc) depend on the protocol though. It would be even more of a pain to deserialize that accordingly if the protocol is in the body. Also, having static formats for messages is much more idiomatic and actually easier to work with in most cases (for the client).
> 
> What exactly was painful about having the protocol in the path?

Let's see how the code looks like but I think the deserialization is not that painful to do.

The issue is lack of consistency between creating a swap ` POST /swaps/rfc003` and   listing swaps `GET /swaps/` (and getting a swap `GET /swaps/rfc003/:id`.

If we can also list RFC-003 swaps via `GET /swaps/rfc003` then it will make it more consistent across the board. But then the question is: do we really need different endpoints?

**Comment by thomaseizinger** [comment] 2019-06-23 11:53
> All in all, I think we may have involuntarily steered away from the scope of this issue.

Looks like it. What do you suggest to discuss the API topic? I wasn't aware that the current design causes problems.

**Comment by D4nte** [comment] 2019-06-23 23:31
> > All in all, I think we may have involuntarily steered away from the scope of this issue.
> 
> Looks like it. What do you suggest to discuss the API topic? I wasn't aware that the current design causes problems.

It'd be more practical if `POST /swaps/rfc003` and `GET /swaps` were the same endpoint

**Comment by tcharding** [comment] 2019-06-24 06:15
FTR JSON now looks like this
```json
{
  "class": [
    "swap"
  ],
  "properties": {
    "counterparty": "QmfUfpC2frwFvcDzpspnfZitHt5wct6n4kpG5jzgRdsxkY",
    "id": "4bb718f5-fa59-4a33-bb72-52553efcc90a",
    "parameters": {
      "alpha_asset": {
        "name": "bitcoin",
        "quantity": "200000000"
      },
      "alpha_ledger": {
        "name": "bitcoin",
        "network": "regtest"
      },
      "beta_asset": {
        "name": "ether",
        "quantity": "20000000000000000000"
      },
      "beta_ledger": {
        "name": "ethereum",
        "network": "regtest"
      },
      "hash_function": "SHA-256"
    },
    "protocol": "rfc003",
    "role": "Bob",
    "status": "IN_PROGRESS"
  },
```

**Comment by tcharding** [comment] 2019-06-24 06:22
Protocol is now left as it was, as a property of the swap.  `hash_function` is added as a parameter.  See JSON above (created from dry tests using `console.log(JSON.stringify, 2, null)`.

**Comment by D4nte** [comment] 2019-07-01 23:28
@tcharding why is it assigned to me? I think you only meant to assign the PR to me, right?

**Comment by tcharding** [comment] 2019-07-02 00:08
> why

My bad, thanks.

**Closed** 2019-07-02 06:55 UTC
Labels: good first issue
