### ISSUE TITLE
Cnd returns the internal error when trying to GET /swaps

### ISSUE THREAD

**Issue by xcchain** [comit-network/comit-rs#2214] opened 2020-03-10 06:29 UTC
## Problem

We’ve updated our cnd to the latest version from master and took the following steps:

1. Deployed 2 cnd nodes on a local machine running on localhost:8000 and localhost:8001 (to do a test swap across two nodes from our DEX app)

2. We send POST localhost:8000/swaps/rfc003 with the following:

```
{
    "alpha_ledger": {
        "name": "bitcoin",
        "network": "testnet"
    },
    "alpha_asset": {
        "name": "bitcoin",
        "quantity": "1000"
    },
    "beta_ledger": {
        "name": "ethereum",
        "chain_id": 3
    },
    "beta_asset": {
        "name": "ether",
        "quantity": "100"
    },
    "alpha_expiry": 1000,
    "beta_expiry": 1000,
    "beta_ledger_redeem_identity": "0xcb46c0e906950CaD69906815e21a84794D5da07a",
    "peer": {
        "peer_id": "QmPea6iEGU5gKSd6JCkPirDXerabYewAHWBY73ujswKYrL",
        "address_hint": "/ip4/127.0.0.1/tcp/9940"
    }
}
```

3. We send GET localhost:8001/swaps and receive this error:

`[2mMar 09 11:46:40.066 [0m  [31mERROR [0m cnd::http_api::problem: internal error occurred: state store did not contain an entry for 48bf8f7f-b8d5-4187-a476-411815a2f414`

**Summary**: the second cnd node does see an ID of the swap request (created on the first cnd node) but cannot retrieve its details, giving us the internal error instead. 

## Goal

Get a list of swaps known by cnd, no error message.

## Proposed solution

1. Investigation
2. Fix

**Comment by thomaseizinger** [comment] 2020-03-10 22:53
Hi @xcchain,

thanks for the report! Would you be able to turn the log level to trace within the config file (use `cnd --dump-config` to explore the format) and send us the logs of both `cnd` when this error happens? That would be really useful.

Thanks!

**Comment by D4nte** [comment] 2020-03-11 02:36
@xcchain `dev` branch is the branch with latest change. `master` only (since recently) contains merge commit for the latest release.
I was not able to pre-reproduce the issue on the `dev` branch. Please try out this branch.

@thomaseizinger can you please proceed with a release now that we have fixed the docker image build?

**Comment by thomaseizinger** [comment] 2020-03-11 07:10
On it: https://github.com/comit-network/comit-rs/issues/2224

**Comment by llilakoblock** [comment] 2020-03-11 10:32
@D4nte
Hi, i've checked dev branch. And have got compilation error:
![image](https://user-images.githubusercontent.com/58418838/76407311-d26e2e80-6393-11ea-808f-de1fbc5b82ce.png)

Win 10, compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x86
No such problem in master branch.

**Comment by thomaseizinger** [comment] 2020-03-11 11:09
> @D4nte
> Hi, i've checked dev branch. And have got compilation error:
> ![image](https://user-images.githubusercontent.com/58418838/76407311-d26e2e80-6393-11ea-808f-de1fbc5b82ce.png)
> 
> Win 10, compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x86
> No such problem in master branch.

We don't support building on Windows at the moment, sorry.

**Comment by llilakoblock** [comment] 2020-03-11 11:21
@D4nte
That's an expected answer, thanks anyway :)

**Comment by thomaseizinger** [comment] 2020-03-12 00:50
For Windows builds, you can subscribe to this issue: https://github.com/comit-network/comit-rs/issues/1407

**Comment by llilakoblock** [comment] 2020-03-16 11:14
Hi, reproducible on Debian GNU/Linux 9.11 (stretch) with latest release.

[2mMar 16 10:52:31.369[0m [32m INFO[0m cnd::db: SQLite database file: /home/eacheveryhour/.local/share/comit/cnd.sqlite
[2mMar 16 10:52:31.369[0m [32m INFO[0m cnd::network: Starting with peer_id: QmYK6jSpg6N4NpsetussTuorNWEJVf1fDoPhxaRLCvgVsE
[2mMar 16 10:52:31.370[0m [34mDEBUG[0m cnd::load_swaps: loading swaps from database ...
[2mMar 16 10:52:31.370[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: cb8effea-4e16-45ee-afbb-cb4ac87a2de0
[2mMar 16 10:52:31.370[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.370[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: 59d114d5-0d10-4fac-972e-89cebb175066
[2mMar 16 10:52:31.370[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.370[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: ce933585-6f95-4593-afeb-a74411b333f9
[2mMar 16 10:52:31.370[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.370[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: e38e22e6-491a-492b-a92d-577954759908
[2mMar 16 10:52:31.370[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.370[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: d9a57dc0-e767-46b6-aa61-18cce2d5a2b7
[2mMar 16 10:52:31.371[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.371[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: c6314f5a-ed3a-4bee-b8e0-80e11bdc0ad1
[2mMar 16 10:52:31.371[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.371[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: d8808540-0489-4363-980a-83d183984581
[2mMar 16 10:52:31.371[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.371[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: 5fc54361-2f99-4285-ad74-201697f1517e
[2mMar 16 10:52:31.371[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.371[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: 0487ca95-53fb-4c5e-93c0-f6c212c6e55c
[2mMar 16 10:52:31.371[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.371[0m [34mDEBUG[0m cnd::load_swaps: got swap from database: 41c9a651-76cd-433d-a936-d65b9836c9c1
[2mMar 16 10:52:31.371[0m [31mERROR[0m cnd::load_swaps: failed to load swap: NotFound, continuing ...
[2mMar 16 10:52:31.371[0m [32m INFO[0m cnd: Starting HTTP server on 0.0.0.0:8001
[2mMar 16 10:54:47.808[0m [31mERROR[0m cnd::http_api::problem: internal error occurred: state store did not contain an entry for cb8effea-4e16-45ee-afbb-cb4ac87a2de0
[2mMar 16 10:54:47.808[0m [32m INFO[0m http: 127.0.0.1:55222 "GET /swaps HTTP/1.1" 500 "-" "test 0.3.0" 403.075µs

**Comment by D4nte** [comment] 2020-03-16 22:35
@llilakoblock Can you please activate trace logs (Use `cnd --dump-config` to know how)?

**Comment by llilakoblock** [comment] 2020-03-17 15:42
@D4nte

[log1.txt](https://github.com/comit-network/comit-rs/files/4344293/log1.txt)
[log2.txt](https://github.com/comit-network/comit-rs/files/4344298/log2.txt)
[config.txt](https://github.com/comit-network/comit-rs/files/4344301/config.txt)
[config2.txt](https://github.com/comit-network/comit-rs/files/4344302/config2.txt)

**Comment by D4nte** [comment] 2020-03-17 23:25
@llilakoblock

I can see that the data dir for both nodes are the same.

Which means they share the same db and seed (this is confirmed by the fact that they both have the same id). This is not expected.

You need to set different data dir for each node. So that each node can have their own id and own db.

Please change/add the/a `[data]` section:

node1:
```
[data]
dir = "/home/llilakoblock/.local/share/comit1"
```

node2:
```
[data]
dir = "/home/llilakoblock/.local/share/comit2"
```

**Comment by D4nte** [comment] 2020-04-07 00:06
Closing now as it seems resolved.

**Closed by D4nte** 2020-04-07 00:06 UTC
Labels: 🐛 bug
