### ISSUE TITLE
⚗️ How to handle COMIT node identification

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#650] opened 2019-01-15 23:50 UTC
Decide how to handle COMIT node identification.
This MUST be compatible with noise, ie, if Alice already knows Bob's id, she needs to be certain she is connected to Bob when negotiating the noise connection.

Most likely public/private key pair, yet to be decided:
- what schema
- how to store locally
- how to backup (if needed)?
- allow alias?
- how to generate

DoD:
- [ ] Proposal in comments
- [ ] New issue that covers the handling and update the `GET connections` api for display

Child of #649

**Comment by thomaseizinger** [comment] 2019-01-15 23:58
Duplicate of #637?

**Closed** 2019-01-16 00:07 UTC
