### ISSUE TITLE
Align comit-rs with new draft of RFC001

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1066] opened 2019-07-02 08:13 UTC
With a [recent](https://github.com/comit-network/RFCs/pull/60) revision of RFC001 the concept of status codes was removed and replaced with a more specialized approach for individual messages.

**Comment by luckysori** [comment] 2019-07-02 09:53
Duplicate of #995.

**Closed by luckysori** 2019-07-02 09:53 UTC
